/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.gephi.ui.importer.plugin;

/**
 *
 * @author ec2-user
 */
public class SolrImportPanel extends javax.swing.JPanel {

    /**
     * Creates new form SolrImportPanel
     */
    public SolrImportPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNodeUrlTextField = new javax.swing.JTextField();
        jNodeQueryTextField = new javax.swing.JTextField();
        jEdgeUrlTextField = new javax.swing.JTextField();
        jEdgeQueryTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jNodeUrlTextField.setText(org.openide.util.NbBundle.getMessage(SolrImportPanel.class, "SolrImportPanel.jNodeUrlTextField.text")); // NOI18N
        jNodeUrlTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNodeUrlTextFieldActionPerformed(evt);
            }
        });

        jNodeQueryTextField.setText(org.openide.util.NbBundle.getMessage(SolrImportPanel.class, "SolrImportPanel.jNodeQueryTextField.text")); // NOI18N
        jNodeQueryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNodeQueryTextFieldActionPerformed(evt);
            }
        });

        jEdgeUrlTextField.setText(org.openide.util.NbBundle.getMessage(SolrImportPanel.class, "SolrImportPanel.jEdgeUrlTextField.text")); // NOI18N
        jEdgeUrlTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEdgeUrlTextFieldActionPerformed(evt);
            }
        });

        jEdgeQueryTextField.setText(org.openide.util.NbBundle.getMessage(SolrImportPanel.class, "SolrImportPanel.jEdgeQueryTextField.text")); // NOI18N
        jEdgeQueryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEdgeQueryTextFieldActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(SolrImportPanel.class, "SolrImportPanel.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(SolrImportPanel.class, "SolrImportPanel.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(SolrImportPanel.class, "SolrImportPanel.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(SolrImportPanel.class, "SolrImportPanel.jLabel4.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jNodeUrlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNodeQueryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEdgeQueryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEdgeUrlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNodeUrlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNodeQueryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jEdgeUrlTextField)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jEdgeQueryTextField)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(126, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jNodeUrlTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNodeUrlTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNodeUrlTextFieldActionPerformed

    private void jEdgeUrlTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEdgeUrlTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEdgeUrlTextFieldActionPerformed

    private void jNodeQueryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNodeQueryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNodeQueryTextFieldActionPerformed

    private void jEdgeQueryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEdgeQueryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEdgeQueryTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jEdgeQueryTextField;
    private javax.swing.JTextField jEdgeUrlTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jNodeQueryTextField;
    private javax.swing.JTextField jNodeUrlTextField;
    // End of variables declaration//GEN-END:variables

    public String getNodeUrl() {
        return jNodeUrlTextField.getText();
    }
    
    public String getNodeQuery() {
        return jNodeQueryTextField.getText();
    }
    
    public String getEdgeUrl() {
        return jEdgeUrlTextField.getText();
    }
    
    public String getEdgeQuery() {
        return jEdgeQueryTextField.getText();
    }
}
